SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS teste_join;
CREATE SCHEMA teste_join;
USE teste_join;

CREATE TABLE TABELA_ALUNOS (
    ID_ALUNO INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    SEXO ENUM('M','F'),
    IDADE INT NOT NULL
);

INSERT INTO TABELA_ALUNOS(ID_ALUNO, NOME, SEXO, IDADE) 
VALUES 
(1, 'João da Silva', 'M', 14),
(2, 'Paulo Antônio', 'M', 13),
(3, 'Maria dos Santos', 'F', 16),
(4, 'Fernanda Madeira', 'F', 13),
(5, 'Paula Aguiar', 'F', 17);


CREATE TABLE TABELA_SALAS(
    ID_SALA CHAR(5) PRIMARY KEY,
    ID_ALUNO INT,
    ANDAR VARCHAR(255),
    SALA CHAR(10)
);

INSERT INTO TABELA_SALAS(ID_SALA, ID_ALUNO, ANDAR, SALA) 
VALUES 
('A1', 2, '1º PRIMEIRO ANDAR', 1001),
('A2', 3, '2º SEGUNDO ANDAR', 2001),
('A3', 1, '1º PRIMEIRO ANDAR', 1002),
('B1', 7, '3º TERCEIRO ANDAR', 3002),
('B2', NULL, '1º SEGUNDO ANDAR', 2002),
('B3', 5, '3º TERCEIRO ANDAR', 3001);

SELECT * FROM tabela_alunos;
SELECT * FROM tabela_salas;